@base = http://localhost:4003

# @name createUser
POST {{base}}/users
Content-Type: application/json

{
    "name": "Henrique",
    "email": "h.botelho@gmail.com",
    "password": "admin",
    "role": "ADMIN"
}

###
GET {{base}}/users


###
GET {{base}}/users/cmbcbmqxb0000tev6suv08xgt


###
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "h.botelho@gmail.com",
    "password": "admin"
}
